name: Attack

on:
  pull_request:
    paths:
      - "test"

jobs:
  attack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Attack files
        run: |
          echo "${{ secrets.MY_SECRET }}" > secret.txt
          cat secret.txt
